import type { SandboxScenario } from './types';

export const SANDBOX_SCENARIOS: SandboxScenario[] = [
  {
    id: 1,
    title: 'Normal User Operations',
    subtext: 'A normal snapshot. The result should stay safe.',
    badge: 'LOW RISK BASELINE',
    badgeClassName: 'bg-aegis-success/10 text-aegis-success border-aegis-success/20',
    telemetry: {
      hostname: 'SANDBOX-VIVA',
      snapshot_label: 'NORMAL_BASELINE',
      accessible_processes: 38,
      pslist_nproc: 40,
      pslist_nppid: 15,
      pslist_avg_threads: 12.4,
      pslist_avg_handlers: 255,
      dlllist_ndlls: 2050,
      dlllist_avg_dlls_per_proc: 47.5,
      handles_nhandles: 11800,
      handles_avg_handles_per_proc: 268,
    },
  },
  {
    id: 2,
    title: 'Resource Intensive Task',
    subtext: 'A busy machine. This should still look safe.',
    badge: 'HIGH RESOURCE',
    badgeClassName: 'bg-aegis-warning/10 text-aegis-warning border-aegis-warning/20',
    telemetry: {
      hostname: 'SANDBOX-VIVA',
      snapshot_label: 'HIGH_RESOURCE',
      accessible_processes: 52,
      pslist_nproc: 54,
      pslist_nppid: 19,
      pslist_avg_threads: 15.8,
      pslist_avg_handlers: 300,
      dlllist_ndlls: 2480,
      dlllist_avg_dlls_per_proc: 51.2,
      handles_nhandles: 14600,
      handles_avg_handles_per_proc: 305,
    },
  },
  {
    id: 3,
    title: 'Simulated Ransomware Behavior',
    subtext: 'A snapshot that looks like ransomware. The result should flag it.',
    badge: 'RANSOMWARE SIM',
    badgeClassName: 'bg-aegis-danger/10 text-aegis-danger border-aegis-danger/20',
    telemetry: {
      hostname: 'SANDBOX-VIVA',
      snapshot_label: 'RANSOMWARE_SIM',
      accessible_processes: 22,
      pslist_nproc: 24,
      pslist_nppid: 9,
      pslist_avg_threads: 9.4,
      pslist_avg_handlers: 192,
      dlllist_ndlls: 980,
      dlllist_avg_dlls_per_proc: 36.5,
      handles_nhandles: 5400,
      handles_avg_handles_per_proc: 195,
    },
  },
];
